# SPDX-License-Identifier: GPL-2.0
#
# Makefile for DPLL drivers.
#

obj-$(CONFIG_DPLL)      += dpll.o
dpll-y                  += dpll_core.o
dpll-y                  += dpll_netlink.o
dpll-y                  += dpll_nl.o

obj-$(CONFIG_DPLL_ZL80X32)	+= zl80x32-dpll.o
zl80x32-dpll-y			+= zl80x32.o
